"""
ComplianceAgent — final guardrail that reviews the Research Card for:
1. No buy/sell/hold language
2. No implied guarantees of returns
3. Standard disclaimer appended
4. Audit log written to local JSON file

Outputs a structured PASS/FAIL verdict + compliant final card.
"""

import json
import os
from datetime import datetime

from google.adk.agents import LlmAgent
from agents.mcp_helpers import make_mcp_toolset



# ---------------------------------------------------------------------------
# Compliance instruction
# ---------------------------------------------------------------------------

_STANDARD_DISCLAIMER = (
    "\n\n---\n"
    "**DISCLAIMER**: This research card is generated by an AI system (EquiSage) for "
    "educational and demonstration purposes only. It does NOT constitute investment advice, "
    "a solicitation to trade, or a guarantee of future returns. Past performance is not "
    "indicative of future results. Always conduct your own due diligence and consult a "
    "SEBI-registered investment adviser before making any financial decisions. "
    "EquiSage is not liable for any financial loss arising from use of this output."
)

_INSTRUCTION = f"""
You are the EquiSage Compliance and Guardrail Agent.

Your job is to review the Research Card produced by the Synthesis Agent and
enforce strict output standards before it is delivered to the user.

## Research Card to Review
{{research_card}}

## Symbol Being Analysed
{{symbol}}

## Compliance Checklist
Work through each item systematically:

### Rule 1: No Buy/Sell/Hold Language
Scan the ENTIRE card for these exact words (case-insensitive):
"buy", "sell", "hold", "purchase", "invest" (as a verb), "recommendation"
If found, REWRITE those sentences to use hedged language:
- "signals suggest" / "the data indicates" / "conviction level suggests"
- Never remove the analytical content, just adjust the framing.

### Rule 2: No Implied Guarantees
Scan for phrases like "will rise", "guaranteed", "certain to", "definitely".
Rewrite to: "may indicate", "historically associated with", "suggests potential for"

### Rule 3: Disclaimer
The final card MUST end with this exact disclaimer:
{_STANDARD_DISCLAIMER}

## Your Output
After reviewing and (if needed) rewriting, produce a JSON response with:

```json
{{{{
  "verdict": "PASS or FAIL",
  "reason": "Describe what you checked, what violations you found (if any), and what you rewrote.",
  "violations_found": ["list of specific violations, or empty list if none"],
  "final_card": "The complete, compliant research card with disclaimer appended."
}}}}
```

CRITICAL: To complete this task, you MUST call the `save_audit_log` tool with your compliance review results (verdict, reason, final_card, symbol). Do NOT output the compliance report as text first; you MUST call the tool. Only after the tool returns the confirmation, output the final compliance JSON report.
"""

from google.adk.models.lite_llm import LiteLlm

compliance_agent = LlmAgent(
    name="ComplianceAgent",
    model=LiteLlm(model="groq/llama-3.3-70b-versatile", num_retries=5),
    instruction=_INSTRUCTION,
    tools=[make_mcp_toolset(tool_filter=["save_audit_log"])],
    output_key="compliance_report",
)
